apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: silverstripe
data:
  config : |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /var/www/public;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass php:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: silverstripe
spec:
  selector:
    app: silverstripe
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32380 # Silverstripe application will be exposed at this port
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: silverstripe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silverstripe
      tier: frontend
  template:
    metadata:
      labels:
        app: silverstripe
        tier: frontend
    spec:
      volumes:
        - name:  app-storage
          persistentVolumeClaim:
            claimName: pvc-app
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: site.conf
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          volumeMounts:
            - name:  app-storage
              mountPath: /var/www
            - name: config
              mountPath: /etc/nginx/conf.d
