apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: silverstripe
spec:
  selector:
    app: silverstripe
    tier: backend
  ports:
    - protocol: TCP
      port: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: silverstripe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: silverstripe
      tier: backend
  template:
    metadata:
      labels:
        app: silverstripe
        tier: backend
    spec:
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: pvc-app
      imagePullSecrets:
        - name: regcred
      containers:
        - name: php
          image: {{image}} # Set by deploy.sh
          imagePullPolicy: "Always"
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/
          lifecycle:
            postStart:
              exec:
                command: ['/bin/sh', '-c', '/bin/postinit.sh']